package com.mycompany.curs;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;
import javax.swing.*;


 */


import com.mycompany.curs.NewJFrame.HuffmanZipCompressor.ProgressUpdater;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class NewJFrame extends javax.swing.JFrame {

     private File selectedFile; 
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        
        jFileChooser1.setDialogTitle("Выберите файл");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("ZIP/DOCX Files", "zip", "docx"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Конвертировать в zip");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Вернуть в docx");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(40, 40, 40)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(48, 48, 48)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1)
                .addGap(87, 87, 87))
            .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, 
                "Сначала выберите файл в проводнике слева!",
                "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fileName = selectedFile.getName().toLowerCase();
    
        if (!fileName.endsWith(".docx")) {
            JOptionPane.showMessageDialog(this, 
                "Пожалуйста, выберите файл с расширением .docx\n"
                + "Выбранный файл: " + selectedFile.getName(),
                "Неверный формат", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String inputPath = selectedFile.getAbsolutePath();
        String outputPath = inputPath.replace(".docx", "_compressed.zip");

        try {
            HuffmanZipCompressor.compressDocxToZip(inputPath, outputPath);
            
            JOptionPane.showMessageDialog(this, 
                "Файл успешно сжат и сохранён как:\n" + outputPath, 
                "Успех", JOptionPane.INFORMATION_MESSAGE);
            

            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "Ошибка при сжатии: " + e.getMessage(),
                "Ошибка", JOptionPane.ERROR_MESSAGE);
  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, 
                "Сначала выберите ZIP-файл в проводнике!",
                "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fileName = selectedFile.getName().toLowerCase();
    
        if (!fileName.endsWith(".zip")) {
            JOptionPane.showMessageDialog(this, 
                "Пожалуйста, выберите файл с расширением .zip\n"
                + "Выбранный файл: " + selectedFile.getName(),
                "Неверный формат", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String inputPath = selectedFile.getAbsolutePath();
        String outputPath = inputPath.replace(".zip", "_restored.docx");

        try {

            HuffmanZipDecompressor.decompressZipToDocx(inputPath, outputPath);
            
            JOptionPane.showMessageDialog(this, 
                "Файл успешно восстановлен как:\n" + outputPath, 
                "Успех", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, 
                "Ошибка при распаковке: " + e.getMessage(),
                "Ошибка", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if (jFileChooser1.getSelectedFile() != null) {
            selectedFile = jFileChooser1.getSelectedFile();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (selectedFile == null) {
        JOptionPane.showMessageDialog(this, "Сначала выберите файл!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String serverAddress = jTextField1.getText().trim();
    if (serverAddress.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Введите адрес сервера!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        byte[] fileData = Files.readAllBytes(selectedFile.toPath());
        
        // Отправка на сервер
        byte[] result = sendToServer("compress", fileData, selectedFile.getName());
        
        // Сохранение результата
        String outputPath = selectedFile.getPath().replace(".docx", "_network.zip");
        Files.write(Paths.get(outputPath), result);
        
        JOptionPane.showMessageDialog(this, "Файл успешно сжат через сеть!", "Успех", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ошибка: " + e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (selectedFile == null) {
        JOptionPane.showMessageDialog(this, "Сначала выберите файл!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String serverAddress = jTextField1.getText().trim();
    if (serverAddress.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Введите адрес сервера!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        byte[] fileData = Files.readAllBytes(selectedFile.toPath());
        
        // Отправка на сервер
        byte[] result = sendToServer("decompress", fileData, selectedFile.getName());
        
        // Сохранение результата
        String outputPath = selectedFile.getPath().replace(".zip", "_network.docx");
        Files.write(Paths.get(outputPath), result);
        
        JOptionPane.showMessageDialog(this, "Файл успешно распакован через сеть!", "Успех", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ошибка: " + e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton4ActionPerformed




private byte[] sendToServer(String command, byte[] fileData, String fileName) throws IOException, ClassNotFoundException {
    try (Socket socket = new Socket(jTextField1.getText().trim(), 12345);
         ObjectOutputStream oos = new ObjectOutputStream(socket.getOutputStream());
         ObjectInputStream ois = new ObjectInputStream(socket.getInputStream())) {
        
        // Отправляем команду и данные
        oos.writeUTF(command);
        oos.writeObject(fileData);
        oos.writeUTF(fileName);
        oos.flush();
        
        // Для декомпрессии нужно отправить дополнительные данные
        if ("decompress".equals(command)) {
            try (ObjectInputStream fileOis = new ObjectInputStream(new ByteArrayInputStream(fileData))) {
                @SuppressWarnings("unchecked")
                Map<Byte, String> huffmanCodes = (Map<Byte, String>) fileOis.readObject();
                int originalSize = fileOis.readInt();
                
                oos.writeObject(huffmanCodes);
                oos.writeInt(originalSize);
                oos.flush();
            }
        }
        
        // Получаем результат
        byte[] result = (byte[]) ois.readObject();
        String resultFileName = ois.readUTF();
        
        return result;
    }
}
    
    /**
     * @param args the command line arguments
     */
    

public static class HuffmanZipCompressor {
    
    
        public static void compressDocxToZip(String inputPath, String outputPath) throws IOException {
            byte[] fileData = Files.readAllBytes(Paths.get(inputPath));

            
            byte[] compressedData = compressWithHuffman(fileData);

            
            try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(outputPath))) {
                ZipEntry entry = new ZipEntry("compressed.huff");
                zos.putNextEntry(entry);
                zos.write(compressedData);
                zos.closeEntry();
            }

        }
        
        public static byte[] compressForNetwork(byte[] data) throws IOException {
        // 1. Построение частотного словаря
        Map<Byte, Integer> frequencyMap = new HashMap<>();
        for (byte b : data) {
            frequencyMap.put(b, frequencyMap.getOrDefault(b, 0) + 1);
        }

        // 2. Построение дерева Хаффмана
        PriorityQueue<HuffmanNode> pq = new PriorityQueue<>();
        for (Map.Entry<Byte, Integer> entry : frequencyMap.entrySet()) {
            pq.add(new HuffmanNode(entry.getKey(), entry.getValue()));
        }

        while (pq.size() > 1) {
            HuffmanNode left = pq.poll();
            HuffmanNode right = pq.poll();
            HuffmanNode parent = new HuffmanNode((byte) 0, left.frequency + right.frequency);
            parent.left = left;
            parent.right = right;
            pq.add(parent);
        }

        HuffmanNode root = pq.poll();

        // 3. Генерация кодов
        Map<Byte, String> huffmanCodes = new HashMap<>();
        generateCodes(root, "", huffmanCodes);

        // 4. Кодирование данных
        StringBuilder encodedData = new StringBuilder();
        for (byte b : data) {
            encodedData.append(huffmanCodes.get(b));
        }

        byte[] compressedBytes = convertBitStringToBytes(encodedData.toString());

        // 5. Упаковка для сети
        ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
        try (ObjectOutputStream objStream = new ObjectOutputStream(byteStream)) {
            objStream.writeUTF("HUFFMAN_v1");
            objStream.writeObject(huffmanCodes);
            objStream.writeInt(data.length);
            objStream.write(compressedBytes);
        }
        return byteStream.toByteArray();
    }
        

        public static byte[] compressWithHuffman(byte[] data) throws IOException{
            Map<Byte, Integer> frequencyMap = new HashMap<>();
            for (byte b : data) {
                frequencyMap.put(b, frequencyMap.getOrDefault(b, 0) + 1);
            }


            PriorityQueue<HuffmanNode> pq = new PriorityQueue<>();
            for (Map.Entry<Byte, Integer> entry : frequencyMap.entrySet()) {
                pq.add(new HuffmanNode(entry.getKey(), entry.getValue()));
            }


            while (pq.size() > 1) {
                HuffmanNode left = pq.poll();
                HuffmanNode right = pq.poll();
                HuffmanNode parent = new HuffmanNode((byte) 0, left.frequency + right.frequency);
                parent.left = left;
                parent.right = right;
                pq.add(parent);
            }


            HuffmanNode root = pq.poll();

            Map<Byte, String> huffmanCodes = new HashMap<>();
            generateCodes(root, "", huffmanCodes);


            StringBuilder encodedData = new StringBuilder();
            for (byte b : data) {
                encodedData.append(huffmanCodes.get(b));
            }


            byte[] compressedBytes = convertBitStringToBytes(encodedData.toString());


            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            try (ObjectOutputStream oos = new ObjectOutputStream(outputStream)) {
                oos.writeObject(huffmanCodes);
                oos.writeInt(data.length);
                oos.write(compressedBytes);
            }

            return outputStream.toByteArray();
        }

        private static void generateCodes(HuffmanNode node, String code, Map<Byte, String> huffmanCodes) {
            if (node == null) return;
            if (node.left == null && node.right == null) {
                huffmanCodes.put(node.data, code);
            }
            generateCodes(node.left, code + "0", huffmanCodes);
            generateCodes(node.right, code + "1", huffmanCodes);
        }

        private static byte[] convertBitStringToBytes(String bitString) {
            int length = (bitString.length() + 7) / 8;
            byte[] bytes = new byte[length];
            for (int i = 0; i < bitString.length(); i++) {
                if (bitString.charAt(i) == '1') {
                    bytes[i / 8] |= (1 << (7 - (i % 8)));
                }
            }
            return bytes;
        }

        static class HuffmanNode implements Comparable<HuffmanNode> {
            byte data;
            int frequency;
            HuffmanNode left, right;

            HuffmanNode(byte data, int frequency) {
                this.data = data;
                this.frequency = frequency;
            }

            @Override
            public int compareTo(HuffmanNode other) {
                return this.frequency - other.frequency;
            }
        }
    

    @FunctionalInterface
    interface ProgressUpdater {
        void update(int value);
    }
    }
    

public static class HuffmanZipDecompressor {
        public static void decompressZipToDocx(String zipPath, String docxPath) 
            throws IOException, ClassNotFoundException {

            try (ZipInputStream zis = new ZipInputStream(new FileInputStream(zipPath))) {
                ZipEntry entry = zis.getNextEntry();
                
                if (!"compressed.huff".equals(entry.getName())) {
                    throw new IOException("Неверный формат архива");
                }
                
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                byte[] buffer = new byte[1024];
                int len;
                while ((len = zis.read(buffer)) > 0) {
                    baos.write(buffer, 0, len);
                }

                
                try (ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(baos.toByteArray()))) {
                    @SuppressWarnings("unchecked")
                    Map<Byte, String> huffmanCodes = (Map<Byte, String>) ois.readObject();

                    int originalSize = ois.readInt();

                    byte[] compressedData = ois.readAllBytes();


                    byte[] originalData = decompressWithHuffman(compressedData, huffmanCodes, originalSize);
                    
                    Files.write(Paths.get(docxPath), originalData);

                }
            }
        }
        
        
        public static byte[] decompressFromNetwork(byte[] networkData) throws IOException, ClassNotFoundException {
        try (ObjectInputStream objStream = new ObjectInputStream(new ByteArrayInputStream(networkData))) {
            // 1. Проверка сигнатуры
            String signature = objStream.readUTF();
            if (!"HUFFMAN_v1".equals(signature)) {
                throw new IOException("Неверный формат сетевых данных");
            }
            
            // 2. Чтение метаданных
            @SuppressWarnings("unchecked")
            Map<Byte, String> huffmanCodes = (Map<Byte, String>) objStream.readObject();
            int originalSize = objStream.readInt();
            byte[] compressedBytes = objStream.readAllBytes();
            
            // 3. Распаковка
            return decompressWithHuffman(compressedBytes, huffmanCodes, originalSize);
        }
    }
        
        
        public static byte[] decompressWithHuffman(byte[] compressedData, 
                                         Map<Byte, String> huffmanCodes,
                                         int originalSize) {
            Map<String, Byte> reverseCodes = new HashMap<>();
            for (Map.Entry<Byte, String> entry : huffmanCodes.entrySet()) {
                reverseCodes.put(entry.getValue(), entry.getKey());
            }

            StringBuilder bitString = new StringBuilder();
            for (byte b : compressedData) {
                String binaryString = String.format("%8s", Integer.toBinaryString(b & 0xFF)).replace(' ', '0');
                bitString.append(binaryString);
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            StringBuilder currentCode = new StringBuilder();
            
            for (int i = 0; i < bitString.length(); i++) {
                currentCode.append(bitString.charAt(i));
                if (reverseCodes.containsKey(currentCode.toString())) {
                    baos.write(reverseCodes.get(currentCode.toString()));
                    currentCode.setLength(0);
                    
                    if (baos.size() == originalSize) {
                        break;
                    }
                }
            }
            
            return baos.toByteArray();
        }
    }


    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
